package id.co.ptn.hungrystock.core.network

const val HOME = "home"
const val AUTH = "login"
const val RESET_PASSWORD = "reset-password"
const val REGISTER = "register"
const val EVENT = "event"
const val LEARNING = "learning"

const val OTP = "otp/userkey=8000"
const val CUSTOMER_LOGIN = "customers-login"
const val PROFILE = "customers"
const val EVENTS = "events"
const val EVENT_CATEGORIES = "event-categories"
const val EVENT_RELATED = "events-related"
const val RESEARCH_CATEGORIES = "research-categories"
const val RESEARCH = "research"
const val BOOKS = "items"
const val WEBINAR = "webinar"
const val CODE_OF_CONDUCT = "pages/page_name=code-of-conduct"